### PR TITLE
docs: move docker and config to sub folder.

### PR DESCRIPTION
**Pull request by appleboy**
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

## 這個 PR 的目的 / Purpose of this PR

1. move all config files to sub-folder.
2. mv docker config files to docker folder

### CODE REVIEW

**Review by chhsiao1981 — CHANGES_REQUESTED** [review]
Dockerfile: requires the corresponding change in scripts/docker_build.sh
* docker build -t ${project}:${branch} -f docker/Dockerfile --build-arg GO_PTTBBS_VERSION=v0.15.3 .

01-config.docker.ini: Requires corresponding change in Dockerfile.
02-config.run.ini: Requires corresponding change in scripts/run.sh

**Comment by appleboy** [comment]
@chhsiao1981 I will update.

**Comment by appleboy** [comment]
@chhsiao1981 Done. Please help to review again.

**Review by chhsiao1981 — APPROVED** [review]
/LGTM

**Pull request merged**
